import type { FreightOffer, OptimizedRoute, RouteSegment } from '../types';
import { AI_MODELS, AI_REQUEST_CONFIG, AI_LIMITS, AI_ENDPOINTS, getApiKey, initializeApiKeys, getAIPromptTemplate } from '../config/aiConfig';

// Initialize API keys from config on module load
initializeApiKeys();

// Module-level variable to store the last AI pagination metadata
let lastAIPaginationMetadata: {
  totalRoutesFound: number;
  returnedRoutesCount: number;
  nextPagePrompt: string | null;
} | null = null;

/**
 * Get the last AI pagination metadata received from the AI service
 */
export function getLastAIPaginationMetadata() {
  return lastAIPaginationMetadata;
}

/**
 * AI-powered route optimization using real AI services (Claude, OpenAI)
 */

interface AIOptimizerConfig {
  maxEmptyRunPercent: number;
  homeBaseLat: number;
  homeBaseLon: number;
  departureFrom: string;
  departureTo: string;
  returnFrom: string;
  returnTo: string;
  averageSpeedKmh: number;
}

interface AIOptimizationResponse {
  routes: OptimizedRoute[];
  reasoning: string;
  confidence: number;
  processingTime: number;
  rawText: string; // Raw AI response text for parsing
  wasLimited?: boolean; // Whether offers were limited due to context size
  originalCount?: number; // Original number of offers
  limitedCount?: number; // Limited number of offers
  metadata?: {
    totalRoutesFound: number;
    returnedRoutesCount: number;
    nextPagePrompt: string | null;
  };
}

interface AIRouteResponse {
  offerIds: string[];
  totalDistanceKm: number;
  loadedDistanceKm: number;
  emptyDistanceKm: number;
  emptyRunPercent: number;
  totalDays: number;
  totalDrivingHours?: number;
  euCompliant: boolean;
  timeOverlap?: boolean;
  score: number;
  reasoning: string;
}

interface AIAPIResponse {
  metadata?: {
    totalRoutesFound: number;
    returnedRoutesCount: number;
    nextPagePrompt: string | null;
  };
  routes: AIRouteResponse[];
  reasoning: string;
  confidence: number;
}

// AI Service configuration (uses centralized config)
const AI_CONFIG = {
  PREFERRED_SERVICE: AI_REQUEST_CONFIG.PREFERRED_SERVICE,
  
  // API endpoints - all go through Vite proxy to avoid CORS
  OPENAI_URL: AI_ENDPOINTS.OPENAI,
  CLAUDE_URL: AI_ENDPOINTS.CLAUDE,
  GROQ_URL: AI_ENDPOINTS.GROQ,
  GEMINI_URL: AI_ENDPOINTS.GEMINI,
  
  // Model settings
  OPENAI_MODEL: AI_MODELS.OPENAI,
  CLAUDE_MODEL: AI_MODELS.CLAUDE,
  GROQ_MODEL: AI_MODELS.GROQ,
  GEMINI_MODEL: AI_MODELS.GEMINI,
  MAX_TOKENS: AI_REQUEST_CONFIG.MAX_TOKENS,
  TEMPERATURE: AI_REQUEST_CONFIG.TEMPERATURE,
};

/**
 * Save AI response to file for debugging
 */
function saveResponseToFile(response: string, processingTime: number): void {
  if (!AI_REQUEST_CONFIG.SAVE_RESPONSES_TO_FILE) return;
  
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `ai-response-${timestamp}.md`;
    
    const debugInfo = `# AI Route Optimization Response
**Timestamp:** ${new Date().toLocaleString('uk-UA')}
**Processing Time:** ${processingTime}ms
**Response Length:** ${response.length} characters

---

## Raw AI Response:
\`\`\`json
${response}
\`\`\`

---

**File:** ${filename}
**Generated by:** Larry Route Planner AI Optimizer
`;

    // Create a blob and download link (for browser environment)
    if (typeof window !== 'undefined') {
      const blob = new Blob([debugInfo], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      console.log(`🤖 Larry AI: Response saved to ${filename}`);
    }
  } catch (error) {
    console.warn('🤖 Larry AI: Failed to save response to file:', error);
  }
}

/**
 * Save AI prompt to file for debugging
 */
function savePromptToFile(prompt: string, config: AIOptimizerConfig, offersCount: number): void {
  if (!AI_REQUEST_CONFIG.SAVE_PROMPTS_TO_FILE) return;
  
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `ai-prompt-${timestamp}.md`;
    
    const debugInfo = `# AI Route Optimization Prompt
**Timestamp:** ${new Date().toLocaleString('uk-UA')}
**Offers Count:** ${offersCount}
**Home Base:** ${config.homeBaseLat}, ${config.homeBaseLon}
**Dates:** ${config.departureFrom} → ${config.returnTo}
**Max Empty:** ${config.maxEmptyRunPercent}%
**Speed:** ${config.averageSpeedKmh} km/h

---

${prompt}

---

**File:** ${filename}
**Generated by:** Larry Route Planner AI Optimizer
`;

    // Create a blob and download link (for browser environment)
    if (typeof window !== 'undefined') {
      const blob = new Blob([debugInfo], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      console.log(`🤖 Larry AI: Prompt saved to ${filename}`);
    }
  } catch (error) {
    console.warn('🤖 Larry AI: Failed to save prompt to file:', error);
  }
}

/**
 * Generate a detailed prompt for AI route optimization using template
 */
async function generateAIPrompt(offers: FreightOffer[], config: AIOptimizerConfig): Promise<string> {
  const offersSummary = offers.map((offer, idx) => {
    const loadingSpot = offer.freight.spots.find(s => 
      s.operations.some(o => o.type === 'loading')
    );
    const unloadingSpot = offer.freight.spots.find(s => 
      s.operations.some(o => o.type === 'unloading')
    );
    
    const loadingOp = loadingSpot?.operations.find(o => o.type === 'loading');
    const unloadingOp = unloadingSpot?.operations.find(o => o.type === 'unloading');
    
    // Format datetime as "DD.MM HH:MM" for compact display
    const formatDT = (iso: string | undefined) => {
      if (!iso) return '-';
      const d = new Date(iso);
      return `${d.getDate().toString().padStart(2,'0')}.${(d.getMonth()+1).toString().padStart(2,'0')} ${d.getHours().toString().padStart(2,'0')}:${d.getMinutes().toString().padStart(2,'0')}`;
    };
    
    const loadBegin = formatDT(loadingOp?.timespan.begin);
    const loadEnd = formatDT(loadingOp?.timespan.end);
    const unloadBegin = formatDT(unloadingOp?.timespan.begin);
    const unloadEnd = formatDT(unloadingOp?.timespan.end);
    
    return `${idx + 1}. ID:${offer.id} | ${loadingSpot?.place.address.locality},${loadingSpot?.place.address.country}→${unloadingSpot?.place.address.locality},${unloadingSpot?.place.address.country} | ${Math.round((offer.freight.route.distance || 0) / 1000)}km | ${offer.price.value || '-'}${offer.price.currency} | Load:${loadBegin}—${loadEnd} | Unload:${unloadBegin}—${unloadEnd} | ${offer.freight.requirements.transport.total_weight || '-'}t | ${loadingSpot?.place.coordinates.latitude.toFixed(3)},${loadingSpot?.place.coordinates.longitude.toFixed(3)}→${unloadingSpot?.place.coordinates.latitude.toFixed(3)},${unloadingSpot?.place.coordinates.longitude.toFixed(3)}`;
  }).join('\n');

  // Load template from MD file
  const template = await getAIPromptTemplate();

  // Replace placeholders in template
  return template
    .replace(/\{\{HOME_LAT\}\}/g, config.homeBaseLat.toString())
    .replace(/\{\{HOME_LON\}\}/g, config.homeBaseLon.toString())
    .replace(/\{\{DEPARTURE_FROM\}\}/g, config.departureFrom)
    .replace(/\{\{DEPARTURE_TO\}\}/g, config.departureTo)
    .replace(/\{\{RETURN_FROM\}\}/g, config.returnFrom)
    .replace(/\{\{RETURN_TO\}\}/g, config.returnTo)
    .replace(/\{\{AVERAGE_SPEED\}\}/g, config.averageSpeedKmh.toString())
    .replace(/\{\{MAX_EMPTY_PERCENT\}\}/g, config.maxEmptyRunPercent.toString())
    .replace(/\{\{OFFERS_COUNT\}\}/g, offers.length.toString())
    .replace(/\{\{OFFERS_LIST\}\}/g, offersSummary);
}

/**
 * Get current API key from config
 */
function getOpenAIKey(): string {
  return getApiKey('openai');
}

function getClaudeKey(): string {
  return getApiKey('claude');
}

function getGroqKey(): string {
  return getApiKey('groq');
}

function getGeminiKey(): string {
  return getApiKey('gemini');
}

/**
 * Call Groq API for route optimization (FREE!)
 */
async function callGroq(prompt: string): Promise<string> {
  const apiKey = getGroqKey();
  if (!apiKey) {
    throw new Error('Groq API key не знайдено. Додайте GROQ_API_KEY в localStorage.');
  }

  console.log('🤖 Larry AI: Calling Groq API (FREE)...');
  
  const response = await fetch(AI_CONFIG.GROQ_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: AI_CONFIG.GROQ_MODEL,
      messages: [{
        role: 'user',
        content: prompt + '\n\nВідповідь надайте ТІЛЬКИ у форматі JSON без додаткового тексту:'
      }],
      max_tokens: AI_CONFIG.MAX_TOKENS,
      temperature: AI_CONFIG.TEMPERATURE,
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    const errorMsg = errorData.error?.message || '';
    
    // Check for context length exceeded
    if (response.status === 400 && (errorMsg.includes('context_length') || errorMsg.includes('too long') || errorMsg.includes('maximum') || errorMsg.includes('reduce the length'))) {
      throw new Error(`CONTEXT_TOO_LONG: Промпт занадто великий для Groq. Автоматично зменшую кількість пропозицій...`);
    }
    
    // Check for token limit exceeded (TPM - tokens per minute)
    if (response.status === 429 && (errorMsg.includes('rate_limit_exceeded') || errorMsg.includes('Request too large') || errorMsg.includes('TPM'))) {
      throw new Error(`CONTEXT_TOO_LONG: Перевищено ліміт токенів Groq. Автоматично зменшую кількість пропозицій...`);
    }
    
    throw new Error(`Groq API error: ${response.status} ${response.statusText}. ${errorMsg}`);
  }

  const data = await response.json();
  
  if (!data.choices || !data.choices[0] || !data.choices[0].message) {
    throw new Error('Неправильна відповідь від Groq API');
  }

  return data.choices[0].message.content;
}

/**
 * Call OpenAI API for route optimization
 */
async function callOpenAI(prompt: string): Promise<string> {
  const apiKey = getOpenAIKey();
  if (!apiKey) {
    throw new Error('OpenAI API key не знайдено. Додайте OPENAI_API_KEY в localStorage.');
  }

  console.log('🤖 Larry AI: Calling OpenAI API...');
  
  const response = await fetch(AI_CONFIG.OPENAI_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: AI_CONFIG.OPENAI_MODEL,
      messages: [{
        role: 'user',
        content: prompt
      }],
      max_tokens: AI_CONFIG.MAX_TOKENS,
      temperature: AI_CONFIG.TEMPERATURE,
      response_format: { type: "json_object" }
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(`OpenAI API error: ${response.status} ${response.statusText}. ${errorData.error?.message || ''}`);
  }

  const data = await response.json();
  
  if (!data.choices || !data.choices[0] || !data.choices[0].message) {
    throw new Error('Неправильна відповідь від OpenAI API');
  }

  return data.choices[0].message.content;
}

/**
 * Call Google Gemini API for route optimization (FREE with high limits!)
 */
async function callGemini(prompt: string): Promise<string> {
  const apiKey = getGeminiKey();
  if (!apiKey) {
    throw new Error('Google Gemini API key не знайдено. Додайте GEMINI_API_KEY в localStorage.');
  }

  console.log('🤖 Larry AI: Calling Google Gemini API (FREE with 1M tokens/min)...');
  
  const response = await fetch(`${AI_CONFIG.GEMINI_URL}?key=${apiKey}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      contents: [{
        parts: [{
          text: prompt + '\n\nВідповідь надайте ТІЛЬКИ у форматі JSON без додаткового тексту:'
        }]
      }],
      generationConfig: {
        temperature: AI_CONFIG.TEMPERATURE,
        maxOutputTokens: AI_CONFIG.MAX_TOKENS,
      }
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    const errorMsg = errorData.error?.message || '';
    
    // Check for rate limit / quota exceeded (429)
    if (response.status === 429) {
      throw new Error(`CONTEXT_TOO_LONG: Перевищено ліміт запитів Gemini (429). Автоматично зменшую кількість пропозицій...`);
    }
    
    throw new Error(`Google Gemini API error: ${response.status} ${response.statusText}. ${errorMsg}`);
  }

  const data = await response.json();
  console.log('🤖 Larry AI: Gemini response data:', JSON.stringify(data, null, 2));
  
  // Check if response structure is valid
  if (!data.candidates || !data.candidates[0]) {
    throw new Error('Неправильна відповідь від Google Gemini API: відсутні candidates');
  }

  const candidate = data.candidates[0];
  
  // Check for MAX_TOKENS finish reason
  if (candidate.finishReason === 'MAX_TOKENS') {
    console.warn('🤖 Larry AI: Gemini response was truncated due to MAX_TOKENS limit');
    throw new Error(`CONTEXT_TOO_LONG: Відповідь Gemini обрізана через ліміт токенів (${AI_CONFIG.MAX_TOKENS}). Автоматично зменшую кількість пропозицій...`);
  }
  
  // Check for other problematic finish reasons
  if (candidate.finishReason && candidate.finishReason !== 'STOP') {
    console.warn('🤖 Larry AI: Gemini finished with reason:', candidate.finishReason);
    throw new Error(`Gemini API завершився з причиною: ${candidate.finishReason}`);
  }

  // Check if content exists and has parts
  if (!candidate.content || !candidate.content.parts || !candidate.content.parts[0]) {
    throw new Error('Неправильна відповідь від Google Gemini API: відсутній контент');
  }

  const responseText = candidate.content.parts[0].text;
  
  // Check if response is empty
  if (!responseText || responseText.trim().length === 0) {
    throw new Error('Gemini API повернув порожню відповідь');
  }

  console.log('🤖 Larry AI: Gemini response text length:', responseText.length);
  return responseText;
}
async function callClaude(prompt: string): Promise<string> {
  const apiKey = getClaudeKey();
  if (!apiKey) {
    throw new Error('Claude API key не знайдено. Додайте CLAUDE_API_KEY в localStorage.');
  }

  console.log('🤖 Larry AI: Calling Claude API...');
  
  const response = await fetch(AI_CONFIG.CLAUDE_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: AI_CONFIG.CLAUDE_MODEL,
      max_tokens: AI_CONFIG.MAX_TOKENS,
      temperature: AI_CONFIG.TEMPERATURE,
      messages: [{
        role: 'user',
        content: prompt + '\n\nВідповідь надайте у форматі JSON:'
      }]
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(`Claude API error: ${response.status} ${response.statusText}. ${errorData.error?.message || ''}`);
  }

  const data = await response.json();
  
  if (!data.content || !data.content[0] || !data.content[0].text) {
    throw new Error('Неправильна відповідь від Claude API');
  }

  return data.content[0].text;
}

/**
 * Extract JSON from AI response text that may contain extra text around it
 */
function extractJSON(text: string): string {
  // Step 1: Try to parse as-is
  const trimmed = text.trim();
  try {
    JSON.parse(trimmed);
    return trimmed;
  } catch { /* continue */ }

  // Step 2: Remove markdown code blocks
  const withoutMarkdown = trimmed.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  try {
    JSON.parse(withoutMarkdown);
    return withoutMarkdown;
  } catch { /* continue */ }

  // Step 3: Find JSON object by matching first { to last }
  const firstBrace = text.indexOf('{');
  const lastBrace = text.lastIndexOf('}');
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    const jsonCandidate = text.substring(firstBrace, lastBrace + 1);
    try {
      JSON.parse(jsonCandidate);
      return jsonCandidate;
    } catch { /* continue */ }
  }

  // Step 4: Try to find JSON array
  const firstBracket = text.indexOf('[');
  const lastBracket = text.lastIndexOf(']');
  if (firstBracket !== -1 && lastBracket !== -1 && lastBracket > firstBracket) {
    // Wrap in object if it's just an array
    const arrayCandidate = text.substring(firstBracket, lastBracket + 1);
    try {
      const parsed = JSON.parse(arrayCandidate);
      if (Array.isArray(parsed)) {
        return JSON.stringify({ routes: parsed, reasoning: '', confidence: 0.7 });
      }
    } catch { /* continue */ }
  }

  // Step 5: Failed - throw with context
  throw new Error(`"${text.substring(0, 100)}..." is not valid JSON`);
}

/**
 * Call AI service for route optimization
 */
async function callAIService(prompt: string): Promise<AIOptimizationResponse> {
  const startTime = Date.now();
  
  try {
    let aiResponseText: string;
    
    // Try preferred service first (Gemini has highest limits!)
    if (AI_CONFIG.PREFERRED_SERVICE === 'gemini' && getGeminiKey()) {
      try {
        aiResponseText = await callGemini(prompt);
      } catch (error) {
        console.warn('🤖 Larry AI: Gemini failed, trying Groq...', error);
        if (getGroqKey()) {
          aiResponseText = await callGroq(prompt);
        } else if (getOpenAIKey()) {
          aiResponseText = await callOpenAI(prompt);
        } else if (getClaudeKey()) {
          aiResponseText = await callClaude(prompt);
        } else {
          throw error;
        }
      }
    } else if (AI_CONFIG.PREFERRED_SERVICE === 'groq' && getGroqKey()) {
      try {
        aiResponseText = await callGroq(prompt);
      } catch (error) {
        console.warn('🤖 Larry AI: Groq failed, trying OpenAI...', error);
        if (getOpenAIKey()) {
          aiResponseText = await callOpenAI(prompt);
        } else if (getClaudeKey()) {
          aiResponseText = await callClaude(prompt);
        } else {
          throw error;
        }
      }
    } else if (AI_CONFIG.PREFERRED_SERVICE === 'openai' && getOpenAIKey()) {
      try {
        aiResponseText = await callOpenAI(prompt);
      } catch (error) {
        console.warn('🤖 Larry AI: OpenAI failed, trying Groq...', error);
        if (getGroqKey()) {
          aiResponseText = await callGroq(prompt);
        } else if (getClaudeKey()) {
          aiResponseText = await callClaude(prompt);
        } else {
          throw error;
        }
      }
    } else if (AI_CONFIG.PREFERRED_SERVICE === 'claude' && getClaudeKey()) {
      try {
        aiResponseText = await callClaude(prompt);
      } catch (error) {
        console.warn('🤖 Larry AI: Claude failed, trying Groq...', error);
        if (getGroqKey()) {
          aiResponseText = await callGroq(prompt);
        } else if (getOpenAIKey()) {
          aiResponseText = await callOpenAI(prompt);
        } else {
          throw error;
        }
      }
    } else {
      // Fallback to any available service (prioritize free Gemini > Groq > paid services)
      if (getGeminiKey()) {
        aiResponseText = await callGemini(prompt);
      } else if (getGroqKey()) {
        aiResponseText = await callGroq(prompt);
      } else if (getOpenAIKey()) {
        aiResponseText = await callOpenAI(prompt);
      } else if (getClaudeKey()) {
        aiResponseText = await callClaude(prompt);
      } else {
        throw new Error('Жоден AI API key не знайдено. Додайте GEMINI_API_KEY (безкоштовно з високими лімітами), GROQ_API_KEY, OPENAI_API_KEY або CLAUDE_API_KEY.');
      }
    }

    const processingTime = Date.now() - startTime;
    console.log(`🤖 Larry AI: Received response in ${processingTime}ms`);
    console.log(`🤖 Larry AI: Raw response (first 500 chars):`, aiResponseText.substring(0, 500));
    
    // Parse AI response - extract JSON from text
    let parsedResponse: AIAPIResponse;
    try {
      const jsonStr = extractJSON(aiResponseText);
      parsedResponse = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error('🤖 Larry AI: Failed to parse AI response:', aiResponseText);
      throw new Error(`Не вдалося розпарсити відповідь AI: ${parseError instanceof Error ? parseError.message : 'Невідома помилка'}`);
    }

    // Store pagination metadata at module level
    if (parsedResponse.metadata) {
      lastAIPaginationMetadata = parsedResponse.metadata;
      console.log('🤖 Larry AI: Pagination metadata:', lastAIPaginationMetadata);
    } else {
      lastAIPaginationMetadata = null;
    }

    return {
      routes: [],
      reasoning: parsedResponse.reasoning || 'AI оптимізація завершена',
      confidence: parsedResponse.confidence || 0.8,
      processingTime,
      rawText: aiResponseText, // Pass raw text for parseAIResponse
      metadata: parsedResponse.metadata,
    };
    
  } catch (error) {
    const processingTime = Date.now() - startTime;
    console.error('🤖 Larry AI: Error calling AI service:', error);
    throw new Error(`AI оптимізація не вдалася (${processingTime}ms): ${error instanceof Error ? error.message : 'Невідома помилка'}`);
  }
}

/**
 * Parse AI response and convert to OptimizedRoute format
 */
function parseAIResponse(
  aiResponseText: string,
  offers: FreightOffer[], 
  config: AIOptimizerConfig
): OptimizedRoute[] {
  console.log('🤖 Larry AI: Parsing AI response...');
  console.log('🤖 Larry AI: Response text length:', aiResponseText.length);
  console.log('🤖 Larry AI: Response preview:', aiResponseText.substring(0, 200));
  
  // Check if response is empty or too short
  if (!aiResponseText || aiResponseText.trim().length < 10) {
    throw new Error('AI повернув порожню або занадто коротку відповідь');
  }
  
  let parsedResponse: AIAPIResponse;
  try {
    const jsonStr = extractJSON(aiResponseText);
    console.log('🤖 Larry AI: Extracted JSON length:', jsonStr.length);
    parsedResponse = JSON.parse(jsonStr);
  } catch (parseError) {
    console.error('🤖 Larry AI: Failed to parse AI response:', aiResponseText.substring(0, 500));
    throw new Error(`Не вдалося розпарсити відповідь AI: ${parseError instanceof Error ? parseError.message : 'Невідома помилка'}`);
  }

  if (!parsedResponse.routes || !Array.isArray(parsedResponse.routes)) {
    console.error('🤖 Larry AI: Invalid response structure:', parsedResponse);
    throw new Error('AI відповідь не містить валідних маршрутів');
  }

  if (parsedResponse.routes.length === 0) {
    console.warn('🤖 Larry AI: AI returned empty routes array');
    throw new Error('AI не знайшов жодного підходящого маршруту');
  }

  const routes: OptimizedRoute[] = [];
  const offerMap = new Map(offers.map(o => [o.id, o]));
  
  console.log(`🤖 Larry AI: Processing ${parsedResponse.routes.length} routes from AI`);
  
  let processedCount = 0;
  let skippedCount = 0;
  
  for (const aiRoute of parsedResponse.routes) {
    try {
      // Validate AI route data
      if (!aiRoute.offerIds || !Array.isArray(aiRoute.offerIds)) {
        console.warn('🤖 Larry AI: Skipping route with invalid offerIds:', aiRoute);
        continue;
      }

      // Find offers for this route
      const routeOffers: FreightOffer[] = [];
      for (const offerId of aiRoute.offerIds) {
        const offer = offerMap.get(offerId);
        if (offer) {
          routeOffers.push(offer);
        } else {
          console.warn(`🤖 Larry AI: Offer ${offerId} not found in available offers`);
        }
      }

      if (routeOffers.length === 0) {
        console.warn('🤖 Larry AI: Skipping route with no valid offers');
        continue;
      }

      // Create route segments
      const segments: RouteSegment[] = routeOffers.map((offer, idx) => {
        const loadingSpot = offer.freight.spots.find(s => 
          s.operations.some(o => o.type === 'loading')
        );
        const unloadingSpot = offer.freight.spots.find(s => 
          s.operations.some(o => o.type === 'unloading')
        );
        
        const loadingDate = loadingSpot?.operations.find(o => o.type === 'loading')?.timespan.begin || new Date().toISOString();
        const unloadingDate = unloadingSpot?.operations.find(o => o.type === 'unloading')?.timespan.begin || new Date().toISOString();
        
        const distanceKm = (offer.freight.route.distance || 0) / 1000;
        const pricePerKm = offer.price.value && distanceKm > 0 ? offer.price.value / distanceKm : null;
        
        // Calculate empty distance (simplified - in real implementation would use routing API)
        let emptyDistanceKm = 0;
        if (idx === 0) {
          // Distance from home base to first loading point
          const loadingCoords = loadingSpot?.place.coordinates;
          if (loadingCoords) {
            emptyDistanceKm = calculateDistance(
              config.homeBaseLat, config.homeBaseLon,
              loadingCoords.latitude, loadingCoords.longitude
            );
          }
        } else {
          // Distance from previous unloading to current loading
          const prevOffer = routeOffers[idx - 1];
          const prevUnloadingSpot = prevOffer.freight.spots.find(s => 
            s.operations.some(o => o.type === 'unloading')
          );
          const currentLoadingSpot = loadingSpot;
          
          if (prevUnloadingSpot && currentLoadingSpot) {
            emptyDistanceKm = calculateDistance(
              prevUnloadingSpot.place.coordinates.latitude,
              prevUnloadingSpot.place.coordinates.longitude,
              currentLoadingSpot.place.coordinates.latitude,
              currentLoadingSpot.place.coordinates.longitude
            );
          }
        }
        
        return {
          offer,
          from: loadingSpot?.place.address.locality || 'Unknown',
          to: unloadingSpot?.place.address.locality || 'Unknown',
          distanceKm,
          loadingDate,
          unloadingDate,
          pricePerKm,
          isEmpty: false,
          emptyDistanceKm,
          drivingHours: distanceKm / config.averageSpeedKmh, // Use configured average speed
          restStops: Math.ceil(distanceKm / (4.5 * config.averageSpeedKmh)), // Break every 4.5h * speed km/h
        };
      });

      // Calculate return distance to home base
      const lastOffer = routeOffers[routeOffers.length - 1];
      const lastUnloadingSpot = lastOffer.freight.spots.find(s => 
        s.operations.some(o => o.type === 'unloading')
      );
      let returnDistanceKm = 0;
      if (lastUnloadingSpot) {
        returnDistanceKm = calculateDistance(
          lastUnloadingSpot.place.coordinates.latitude,
          lastUnloadingSpot.place.coordinates.longitude,
          config.homeBaseLat,
          config.homeBaseLon
        );
      }

      // Use AI provided values or calculate from segments
      // IMPORTANT: Use !== undefined check because 0 is a valid value
      const totalLoaded = aiRoute.loadedDistanceKm !== undefined ? aiRoute.loadedDistanceKm : segments.reduce((sum, s) => sum + s.distanceKm, 0);
      
      // Calculate empty distance ourselves (more accurate than AI which sometimes miscalculates)
      const calculatedEmpty = segments.reduce((sum, s) => sum + s.emptyDistanceKm, 0) + returnDistanceKm;
      const aiEmpty = aiRoute.emptyDistanceKm !== undefined ? aiRoute.emptyDistanceKm : calculatedEmpty;
      
      // Use the LARGER of AI's value vs our calculation (AI sometimes underestimates)
      const totalEmpty = Math.max(aiEmpty, calculatedEmpty);
      
      const totalDistance = totalLoaded + totalEmpty;
      const emptyPercent = totalDistance > 0 ? (totalEmpty / totalDistance) * 100 : 0;
      const totalDriving = aiRoute.totalDrivingHours !== undefined ? aiRoute.totalDrivingHours : (segments.reduce((sum, s) => sum + s.drivingHours, 0) + (returnDistanceKm / config.averageSpeedKmh));
      
      // Log info but DON'T filter — user decides what routes to use
      if (emptyPercent > config.maxEmptyRunPercent) {
        console.info(`🤖 Larry AI: Route has ${emptyPercent.toFixed(1)}% empty run (target: <${config.maxEmptyRunPercent}%)`);
      }
      if (segments.length < 2) {
        console.info(`🤖 Larry AI: Single-offer route (${segments.length} offers)`);
      }

      processedCount++;

      const optimizedRoute: OptimizedRoute = {
        segments,
        totalDistanceKm: totalDistance,
        loadedDistanceKm: totalLoaded,
        emptyDistanceKm: totalEmpty,
        emptyRunPercent: emptyPercent,
        totalDays: aiRoute.totalDays || Math.ceil(totalDriving / 9),
        idleHours: 0,
        totalDrivingHours: aiRoute.totalDrivingHours || totalDriving,
        totalRestHours: Math.ceil(totalDriving / 9) * 11,
        mandatoryBreaks: Math.ceil(totalDriving / 4.5),
        weeklyRestsNeeded: Math.ceil(Math.ceil(totalDriving / 9) / 6),
        score: aiRoute.score || 80,
        euCompliant: aiRoute.euCompliant !== undefined ? aiRoute.euCompliant : totalDriving <= 56,
        timeOverlap: aiRoute.timeOverlap || false,
      };

      routes.push(optimizedRoute);
      
    } catch (routeError) {
      console.error('🤖 Larry AI: Error processing route:', routeError, aiRoute);
      // Continue with other routes - don't increment counters for errors
    }
  }

  console.log(`🤖 Larry AI: Successfully parsed ${routes.length} routes from AI response (processed: ${processedCount})`);
  
  if (routes.length === 0) {
    throw new Error('Не вдалося створити жодного валідного маршруту з AI відповіді');
  }
  
  return routes;
}

/**
 * Calculate distance between two coordinates using Haversine formula (in km)
 */
function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth's radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c * 1.3; // Add 30% for road distance vs straight line
}

/**
 * Load next page of AI routes using the nextPagePrompt from pagination metadata
 */
export async function loadNextAIPage(
  nextPagePrompt: string,
  offers: FreightOffer[],
  config: AIOptimizerConfig,
  statusCallback?: (status: string) => void
): Promise<OptimizedRoute[]> {
  console.log('🤖 Larry AI: Loading next page of AI routes...');
  if (statusCallback) statusCallback('🤖 Завантажую наступну порцію маршрутів...');

  try {
    // Send the nextPagePrompt directly as the full prompt to the AI
    const aiResponse = await callAIService(nextPagePrompt);

    console.log('🤖 Larry AI: Received next page response, parsing...');

    // Save AI response to file for debugging
    saveResponseToFile(aiResponse.rawText, aiResponse.processingTime);

    // Parse and convert AI response to OptimizedRoute format
    const routes = parseAIResponse(aiResponse.rawText, offers, config);

    console.log(`🤖 Larry AI: Next page returned ${routes.length} additional routes`);
    if (statusCallback) statusCallback(`✅ Завантажено ще ${routes.length} маршрутів`);

    return routes;
  } catch (error) {
    console.error('🤖 Larry AI: Error loading next page:', error);
    const errorMessage = error instanceof Error ? error.message : 'Невідома помилка';
    if (statusCallback) statusCallback(`❌ Помилка завантаження: ${errorMessage}`);
    throw new Error(`Не вдалося завантажити наступну сторінку: ${errorMessage}`);
  }
}

/**
 * Main AI optimization function
 */
export async function buildAIOptimizedRoutes(
  offers: FreightOffer[] | { mainOffers: FreightOffer[]; returnOffers: FreightOffer[] },
  config: AIOptimizerConfig,
  statusCallback?: (status: string) => void
): Promise<OptimizedRoute[]> {
  console.log('🤖 Larry AI: Starting AI-powered route optimization...');
  
  // Normalize input
  let mergedOffers: FreightOffer[];
  if (Array.isArray(offers)) {
    mergedOffers = offers;
  } else {
    const { mainOffers, returnOffers } = offers;
    const seen = new Set<string>();
    mergedOffers = [];
    
    for (const o of mainOffers) {
      if (!seen.has(o.id)) {
        seen.add(o.id);
        mergedOffers.push(o);
      }
    }
    for (const o of returnOffers) {
      if (!seen.has(o.id)) {
        seen.add(o.id);
        mergedOffers.push(o);
      }
    }
  }
  
  if (mergedOffers.length === 0) {
    console.log('🤖 Larry AI: No offers to optimize');
    return [];
  }
  
  console.log(`🤖 Larry AI: Optimizing ${mergedOffers.length} offers using real AI service`);
  
  // Step 1: Soft pre-filter — тільки відкидаємо пропозиції де завантаження ДО дати виїзду
  // Решту рішень приймає AI і позначає ризики
  const depFrom = new Date(config.departureFrom);
  
  const dateFilteredOffers = mergedOffers.filter(offer => {
    const loadingSpot = offer.freight.spots.find(s => 
      s.operations.some(o => o.type === 'loading')
    );
    
    const loadingDate = loadingSpot?.operations.find(o => o.type === 'loading')?.timespan.begin;
    
    // Тільки відкидаємо пропозиції де завантаження ДО дати виїзду (фізично неможливо)
    if (loadingDate) {
      const loadDate = new Date(loadingDate);
      if (loadDate < depFrom) return false;
    }
    
    return true;
  });
  
  if (dateFilteredOffers.length < mergedOffers.length) {
    const removed = mergedOffers.length - dateFilteredOffers.length;
    const message = `🗓️ Відфільтровано ${removed} пропозицій за датами (не вкладаються в ${config.departureFrom} — ${config.returnTo})`;
    console.log(`🤖 Larry AI: ${message}`);
    if (statusCallback) statusCallback(`🤖 ${message}`);
  }
  
  if (dateFilteredOffers.length === 0) {
    console.log('🤖 Larry AI: No offers match date range after filtering');
    return [];
  }
  
  // Step 2: Limit offers to fit within AI context window
  // Gemini 2.0 Flash: 1M context but rate limited on requests per minute
  // Each offer line is ~200 chars ≈ ~50 tokens
  // Keep prompt under ~30KB to avoid rate limits
  const MAX_OFFERS_FOR_AI = AI_LIMITS.MAX_OFFERS_FOR_AI;
  let offersForAI = dateFilteredOffers;
  let wasLimited = false;
  
  if (dateFilteredOffers.length > MAX_OFFERS_FOR_AI) {
    wasLimited = true;
    const message = `⚠️ Забагато пропозицій (${dateFilteredOffers.length}), обмежую до ${MAX_OFFERS_FOR_AI} найкращих`;
    console.log(`🤖 Larry AI: ${message}`);
    if (statusCallback) statusCallback(`🤖 ${message}...`);
    
    // Score and sort offers by relevance:
    // - Higher price per km = better
    // - Reasonable distance (not too short, not too long) = better  
    // - Closer to other offers (for chaining) = better
    offersForAI = [...dateFilteredOffers]
      .map(offer => {
        const loadingSpot = offer.freight.spots.find(s => 
          s.operations.some(o => o.type === 'loading')
        );
        const distKm = (offer.freight.route.distance || 0) / 1000;
        const pricePerKm = offer.price.value && distKm > 0 ? offer.price.value / distKm : 0;
        
        // Distance from home to loading point
        const loadLat = loadingSpot?.place.coordinates.latitude || 0;
        const loadLon = loadingSpot?.place.coordinates.longitude || 0;
        const distFromHome = Math.sqrt(
          Math.pow(loadLat - config.homeBaseLat, 2) + 
          Math.pow(loadLon - config.homeBaseLon, 2)
        ) * 111; // rough km conversion
        
        // Prefer routes that are:
        // 1. High price per km (most important)
        // 2. Good distance (300-800km sweet spot)
        // 3. Not too far from home base
        const distanceScore = distKm > 200 && distKm < 1000 ? 1.5 : 1.0; // Bonus for good distances
        const homeDistanceScore = distFromHome < 500 ? 1.2 : 1.0; // Bonus for reasonable home distance
        
        const score = pricePerKm * 100 * distanceScore * homeDistanceScore + distKm * 0.3;
        
        return { offer, score, pricePerKm, distKm, distFromHome };
      })
      .sort((a, b) => b.score - a.score)
      .slice(0, MAX_OFFERS_FOR_AI)
      .map(item => item.offer);
    
    console.log(`🤖 Larry AI: Selected top ${offersForAI.length} offers by relevance score`);
    if (statusCallback) statusCallback(`🤖 Відібрано ${offersForAI.length} найкращих пропозицій...`);
  }
  
  try {
    // Generate AI prompt
    const prompt = await generateAIPrompt(offersForAI, config);
    console.log(`🤖 Larry AI: Generated prompt (${prompt.length} characters, ${offersForAI.length} offers)`);
    
    // Save prompt to file for debugging
    savePromptToFile(prompt, config, offersForAI.length);
    
    if (wasLimited) {
      console.log(`🤖 Larry AI: ⚠️ Prompt was limited from ${mergedOffers.length} to ${offersForAI.length} offers to fit AI context window`);
    }
    console.log(`🤖 Larry AI: === PROMPT START ===\n${prompt}\n=== PROMPT END ===`);
    
    // Call real AI service
    let aiResponse;
    try {
      aiResponse = await callAIService(prompt);
    } catch (firstError) {
      // If context too long, retry with fewer offers
      if (firstError instanceof Error && firstError.message.includes('CONTEXT_TOO_LONG') && offersForAI.length > AI_LIMITS.MIN_OFFERS_FOR_RETRY) {
        const reducedCount = Math.floor(offersForAI.length * AI_LIMITS.RETRY_REDUCTION_PERCENT);
        const message = `⚠️ Контекст занадто великий, зменшую до ${reducedCount} пропозицій`;
        console.log(`🤖 Larry AI: ${message} (було ${offersForAI.length})`);
        if (statusCallback) statusCallback(`🤖 ${message}...`);
        
        const reducedOffers = offersForAI.slice(0, reducedCount);
        const reducedPrompt = await generateAIPrompt(reducedOffers, config);
        console.log(`🤖 Larry AI: Reduced prompt (${reducedPrompt.length} characters, ${reducedOffers.length} offers)`);
        
        // Save reduced prompt to file
        savePromptToFile(reducedPrompt, config, reducedOffers.length);
        
        try {
          aiResponse = await callAIService(reducedPrompt);
        } catch (secondError) {
          // If still too long, try with even fewer
          if (secondError instanceof Error && secondError.message.includes('CONTEXT_TOO_LONG') && reducedCount > 10) {
            const minCount = Math.min(AI_LIMITS.MIN_OFFERS_FOR_RETRY, Math.floor(reducedCount * 0.5));
            const finalMessage = `⚠️ Все ще занадто великий, зменшую до ${minCount} пропозицій`;
            console.log(`🤖 Larry AI: ${finalMessage}`);
            if (statusCallback) statusCallback(`🤖 ${finalMessage}...`);
            
            const minOffers = offersForAI.slice(0, minCount);
            const minPrompt = await generateAIPrompt(minOffers, config);
            
            // Save final reduced prompt to file
            savePromptToFile(minPrompt, config, minOffers.length);
            
            aiResponse = await callAIService(minPrompt);
          } else {
            throw secondError;
          }
        }
      } else {
        throw firstError;
      }
    }
    
    console.log('🤖 Larry AI: Received AI response, parsing...');
    
    // Save AI response to file for debugging
    saveResponseToFile(aiResponse.rawText, aiResponse.processingTime);
    
    // Parse and convert AI response to OptimizedRoute format
    const routes = parseAIResponse(aiResponse.rawText, mergedOffers, config);
    
    console.log(`🤖 Larry AI: Successfully generated ${routes.length} AI-optimized routes`);
    console.log(`🤖 Larry AI: Processing time: ${aiResponse.processingTime}ms`);
    console.log(`🤖 Larry AI: Confidence: ${(aiResponse.confidence * 100).toFixed(1)}%`);
    console.log(`🤖 Larry AI: AI Reasoning: ${aiResponse.reasoning}`);
    
    return routes;
    
  } catch (error) {
    console.error('🤖 Larry AI: Error during AI optimization:', error);
    
    // Show user-friendly error message
    const errorMessage = error instanceof Error ? error.message : 'Невідома помилка';
    
    // Throw error so App.tsx can display it properly
    console.error('🤖 Larry AI: Error:', errorMessage);
    throw new Error(`AI оптимізація не вдалася: ${errorMessage}`);
  }
}